apiVersion: v1
kind: Service
metadata:
  name: {{ include "cdn-origin-controller.name" . }}-{{ .Values.cdnClass }}
  labels:
{{ include "cdn-origin-controller.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cdn-origin-controller.name" . }}-{{ .Values.cdnClass }}
    app.kubernetes.io/instance: {{ .Release.Name }}
