{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cdn-origin-controller.serviceAccountName" . }}
  labels:
{{ include "cdn-origin-controller.labels" . | indent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end -}}
{{- end -}}