# permissions for end users to view cdnclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdnclass-viewer-role
rules:
- apiGroups:
  - cdn.gympass.com
  resources:
  - cdnclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdn.gympass.com
  resources:
  - cdnclasses/status
  verbs:
  - get
