# permissions for end users to view cdnstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdnstatus-viewer-role
rules:
- apiGroups:
  - cdn.gympass.com
  resources:
  - cdnstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdn.gympass.com
  resources:
  - cdnstatuses/status
  verbs:
  - get
