replicaCount: 1

image:
  repository: ghcr.io/gympass/cdn-origin-controller
  tag: v0.0.8
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  annotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

podSecurityContext: {}
 # fsGroup: 65532

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

envs: {}
