replicaCount: 1

cdnClass: default

image:
  repository: ghcr.io/gympass/cdn-origin-controller
  tag: v0.4.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraArgs:
  #- --leader-elect

deployment:
  annotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

podSecurityContext: {}
 # fsGroup: 65532

securityContext: {}

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

envs: {}

cdnClasses: []
# - name: ""
#   certificateArn: ""
#   hostedZoneID: ""
