name: PR Checks
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "Makefile"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - main
      - develop
env:
  GO_VERSION: '1.20'
jobs:
  golint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          args: --enable=revive --timeout=2m
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Generate, format and vet
        run: |
          make generate
          make manifests
          make fmt
          make vet
          changed_files=$(git status -s || :)
          generated_changed_files=$(git status -s | grep zz_generated || :)
          [[ -z "$generated_changed_files" ]] || (printf "There is change in auto-generated files" && exit 1)
          [[ -z "$changed_files" ]] ||  (printf "Change is detected in some files: \n$changed_files\n" && exit 1)
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Test Packages
        run: make test
