name: Sonarcloud Tests
on: push
jobs:
  Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}